### ISSUE TITLE
npm install of 1.4 failing

### ISSUE THREAD

**Issue by chrisdrackett** [HubSpot/drop#123]
```
npm ERR! tether-drop@1.4.0 install: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the tether-drop@1.4.0 install script 'bower install'.
npm ERR! This is most likely a problem with the tether-drop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls tether-drop
npm ERR! There is likely additional logging output above.
```

**Comment by geekjuice** [comment]
What version of `node` and `npm` are you running? Can't seem to reproduce in `0.10.36`, `0.12.7`, and `v4.2.1`.

**Comment by chrisdrackett** [comment]
npm 2.11.2
node 0.12.5

**Comment by geekjuice** [comment]
Actually, I'm gonna guess that the install is failing because `bower` isn't installed. Can you try running `npm install -g bower` and trying the install again?

I do plan to remove that step at some point, but it was there as a convenience for those wanting to just install `tether-drop` and not worry about its deps.

**Comment by chrisdrackett** [comment]
that seems to have fixed it.

**Comment by geekjuice** [comment]
Awesome. I'll create an issue regarding the removing the `bower post-install` step so this isn't an issue in the future :beers:
