### ISSUE TITLE
Uncaught Error: Drop Error: You must provide a target.

### ISSUE THREAD

**Issue by webchaz** [HubSpot/drop#47]
I keep getting this error, I get it in the documentation as well when I try to Run the code.

I'm just trying to setup a very simple test and I've done:

```
        drop = new Drop({
          target: document.querySelector('.drop-target'),
          content: 'Welcome to the future!',
          position: 'bottom left',
          openOn: 'click'
        });
```

and

```
      <div class="example-inner">
          <a class="drop-target drop-target-example-drop-theme-arrows-bounce-dark">Size</a>
          <div class="drop-content">
              <input type="range" />
          </div>
      </div>
```

Is this correct? or am I missing something...

Thank you

**Comment by geekjuice** [comment]
So it seems like that example in our documentation shouldn't be executable because there actually isn't an element with class `.drop-target` on that page. Basically, you need to make sure that the `target` you are attaching your `Drop` to exists in the __DOM__. So for your example, double check that you are attaching your `Drop` after the __DOM__ has been loaded and that the element you are choosing as the `target` exists before you initialize your `Drop` instance.

Here's a [jsFiddle](http://jsfiddle.net/comp46g9/2/) to show how to get the range example working (albeit lacking much styles).
