### ISSUE TITLE
Positioning bug when using div position: absolute 

### ISSUE THREAD

**Issue by stevenh77** [HubSpot/drop#57]
I seem to be having an issue with the drop Y positioning incorrectly when the target is contained in a div with absolute positioning.

Here is the demo:  http://stevenhollidge.com/drop-ng/example/wijmo-grid/positioning-bug.html

I need to be able to use absolute positioning, any ideas what's going wrong and how best to solve?  

Hope you can help!

Broken: 
![positioning-bug](https://cloud.githubusercontent.com/assets/307670/6598835/309cc7fa-c7fe-11e4-9dd9-4e3f251265b4.PNG)

Fix:
![fix](https://cloud.githubusercontent.com/assets/307670/6598842/36fe97fe-c7fe-11e4-88fb-902986550829.PNG)

**Comment by stevenh77** [comment]
Here's a simplified pure dropJS example (without Wijmo Angular or drop-ng):
http://stevenhollidge.com/drop-ng/example/positioning-bug/

Bug:
![bug](https://cloud.githubusercontent.com/assets/307670/6646348/e44fefa2-c9bb-11e4-9c78-2822966ab7b4.PNG)

Fix: 
![fix](https://cloud.githubusercontent.com/assets/307670/6646350/e7fed488-c9bb-11e4-925e-a4346eb482e2.PNG)

Any suggestions would be much appreciated :)

**Comment by geekjuice** [comment]
The issue seems to be that the parent element of all the of `position: absolute` children do not have a height because of the absolute positioning of the child element. This is due to the face that once an element is positioned absolutely, it is taken out of the flow of the parent container which is why the `Drops` are being positions at the top of the parent containers. 

If you actually add `height` to some value that will contain the child element, you will see the `Drop` positioned correctly. YMMV so this may not be the solution you were looking for, but if you can either add some height to the parent container or avoid absolute positioning, that would solve the problem.

**Comment by geekjuice** [comment]
__No height on parent container:__

![stevenhollidge_com_drop-ng_example_positioning-bug_](https://cloud.githubusercontent.com/assets/1654587/6647078/5d7a63f0-c9a1-11e4-8b35-05f96b1916cb.png)

__Some height on parent container:__
![stevenhollidge_com_drop-ng_example_positioning-bug_](https://cloud.githubusercontent.com/assets/1654587/6647118/8fa7d56a-c9a1-11e4-9529-f0d7cf890332.png)

**Comment by stevenh77** [comment]
Nice one Nicholas, thanks for your help!
