### ISSUE TITLE
close option?

### ISSUE THREAD

**Issue by janusch** [HubSpot/drop#82]
Nice work on tether and drop!

I just looked at it the first time and made an example. Somehow i cannot get the drop to close again.
Is there a data-attribute that can be used for it?

What I would like is a drop that opens on hover and stays sticky when the mouse is within the drop, is that functionality somehow baked into the lib? 
Or how would you go about extending it?

Keep up the good work!

**Comment by geekjuice** [comment]
Glad you like the library! :smile_cat: Regarding closing the drop, the drop instance has [methods](http://github.hubspot.com/drop/#methods) you can call to close it explicitly if your `openOn` option is something other than `hover or click`. 

Also, the drop should already stay open when you hover over the drop. You would need to pass `openOn: hover` as one of the attributes though when you are constructing the drop since drop defaults to `openOn: click`:

```javascript
const dropInstance = new Drop({
    target: document.querySelector('.drop-target'),
    content: 'I will appear in the drop!',
    classes: 'drop-theme-twipsy',
    openOn: 'hover'
});
```

**Comment by janusch** [comment]
@geekjuice Thank you for the quick clarification. I am going to give drop another shot, hopefully it canbe used for my project.

Keep up the great work!

**Comment by geekjuice** [comment]
Awesome! Feel free to let me know if run into any issues and I'll be happy to help you out :smile_cat:
