### ISSUE TITLE
Add note in README and docs about including style

### ISSUE THREAD

**Issue by geekjuice** [HubSpot/drop#90]
The current demo site, README, and docs hint at including a theme, but does not explicitly state that it should be added. This can cause some initial confusion since it may seem like the open, close, etc. functionality is not working.

In addition to that note, we should reconsider a default theme to use in the `classes` field (maybe `drop-theme-arrow` since it's shown in the welcome site) and/or look into auto loading styles default styles is none provided.

**Comment by dandv** [comment]
I've also seen something related - drops open but the CSS is missing, even though I included the stylesheet. Turns out I forgot to declare the correct `classes: 'drop-theme-arrows',` option.

Would it be possible for the drop to dynamically load the required CSS if a certain parameter were passed? At the simplest, it could look for '../css/' + classes + 'css'.

**Comment by geekjuice** [comment]
I wished it was as easy as that (maybe it is and I just don't know), but the the only way I can think of to accomplish this would be to loop through `document.styleSheets` for every CSS rule in search of the theme classes and applying them dynamically it they exists.

I have/am considering including an add-on script for dynamic theme loading using the above technique if it's something that others would find useful though.
