### ISSUE TITLE
Not working in absolutely positioned DIVs/when body height is zero

### ISSUE THREAD

**Issue by arapoport** [HubSpot/drop#95]
Hi!

I found your library and wanted to give it a try. But popover did not appear :-) After short investigation in Chrome I found out, that the popover element was outside of the visible area, even outside of the page (probably because of translateY(-54px) style it had). 

I don't have any demo that I can share. I'll describe it briefly.

I attached the Drop instance to a button placed inside of an absolutely positioned div. The body of the page had zero height.

OpenUI5 Popover has no problem being attached to the same element...

drop.js 1.2.1 with drop-theme-arrows.css
tether.js 1.0.2

**Comment by geekjuice** [comment]
Because of how `tether` works, you may need to add a constraint to keep the `drop` in the viewport.  [[jsFiddle]](http://jsfiddle.net/uj4zLaks/1/) You can also take a look at the various options you can use for constraints [here](http://github.hubspot.com/tether/#constraints) in the `tether` documentation to fit your specific need.
